; Developer magic
projects[devel][subdir] 				= development
projects[devel_themer][subdir] 			= development
projects[coder][subdir] 				= development
projects[examples][subdir] 				= development
projects[pqp][subdir] 					= development
projects[hacked][subdir] 				= development
projects[module_builder][subdir] 		= development
projects[profiler][subdir] 				= development
projects[simpletest][subdir] 			= development
projects[XHProf][subdir] 				= development
projects[querypath][subdir] 			= contrib