; Developer modules
projects[coder][subdir] 				= development
projects[coder_tough_love][subdir] 		= development
projects[devel][subdir] 				= development
projects[devel_themer][subdir] 			= development
projects[profiling][subdir] 			= development
;projects[pqp][subdir] 					= development
;projects[profiler][subdir] 			= development
;projects[debugger][subdir] 			= development
;projects[dbtuner][subdir] 				= development
;projects[dtools][subdir] 				= development
;projects[devel_demo][subdir] 			= development
;projects[drupalforfirebug][subdir] 	= development
;projects[drush_make_ui][subdir] 		= development
;projects[examples][subdir] 			= development
;projects[views_examples][subdir] 		= development
;projects[firebug_lite][subdir] 		= development
;projects[hacked][subdir] 				= development
;projects[keys][subdir] 			    = development
;projects[module_builder][subdir] 		= development
;projects[simpletest][subdir] 			= development
;projects[testing_server_setup][subdir] = development
;projects[trace][subdir] 				= development
projects[apachebench][subdir] 			= development

;projects[environment_indicator][subdir]	= development
;projects[environments][subdir] 			= development
;projects[masquerade][subdir] 				= development

;projects[selenium][download][modules] = development
;projects[selenium][download][type] = cvs
;projects[selenium][revision] = HEAD

projects[diff][subdir]		 			= contrib
projects[ctools][subdir] 				= contrib
;projects[potx][subdir] 				= contrib
;projects[services][subdir] 			= contrib
;projects[schema][subdir] 				= contrib
;projects[popups][subdir] 				= contrib
;projects[security_review][subdir] 		= contrib
;projects[md5check][subdir] 			= contrib
;projects[job_queue][subdir] 			= contrib
;projects[queryable_variables][subdir] 	= contrib
;projects[security_scanner][subdir] 	= contrib
;projects[modalframe][subdir] 			= contrib
;projects[data][subdir] 				= contrib
;projects[querypath][subdir] 			= contrib
;projects[dbtng][subdir] 				= contrib